version: '3.3'
services:
  backend:
    env_file:
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
  celeryworker:
    env_file:
      - env-backend.env
    environment:
      - SERVER_HOST=https://${DOMAIN}
